/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DataNFT__factory } from "./DataNFT__factory";
export { Marketplace__factory } from "./Marketplace__factory";
